; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s9, Segoe UI
Gui Add, Picture, x8 y8 w150 h150, %A_ScriptDir%\images\Logo.png
Gui Add, Text, x1200 y8 w700 h23 +0x200   , How to setup manually your own resolution:
Gui Add, Text, x1200 y31 w700 h23, 1 - Click on "Add New Resolution Config" Button and set a name for it
Gui Add, Text, x1200 y54 w700 h23, 2 - Click on the button of the tool that you will change the position
Gui Add, Text, x1200 y77 w700 h23, 3 - Go to your software screen and position the mouse on top of the tool
Gui Add, Text, x1200 y100 w700 h23, 4 - Hit "ENTER" key to save that position - If you think you made a mistake, you can hit "Enable Last Button" and do that tool again
Gui Add, Text, x1200 y123 w700 h23, 5 - Repeat the process for each tool and after do it for all the tools, hit "Save Positions" button
Gui Add, Text, x1200 y146 w700 h23, * Please wait 5 to 10 seconds to do anything else on the software after hit "Save Positions" button
Gui Add, Button, g_start_stop_bt x192 y8 w150 h50, Stop TWB
Gui Add, Button, g_save_positions_bt x192 y64 w150 h50, Save Positions
Gui Add, Button, g_enable_last_button x192 y120 w150 h50, Enable Last Button
Gui Add, Button, g_add_combobox_items_input_box x790 y8 w150 h50, Add New Resolution Config
Gui Add, Text, x360 y8 w250 h23, Set Resolution / DPI Scale (in percentage):
Gui Add, ComboBox, vcomboboxResolutionScale g_change_resolution_and_scale x360 y32 w400, %_comboboxResolutionItems%
Gui Add, Text, x360 y64 w250 h23, Set what is your Davinci Resolve Layout:
Gui Add, ComboBox, vcomboboxDavinciLayoutUI g_change_davinci_layout_ui x360 y90 w400, NORMAL|CONDENSED|WIDE
Gui Add, Text, x360 y120 w250 h23, Set a type of curves Hashs:
Gui Add, ComboBox, vcomboboxCurvesHashs g_change_curves_hash x360 y148 w100, 1|2|3
Gui Add, CheckBox, vscopesState g_set_scopes_state x790 y90 w403 h23, Check this box if your scopes window is floating
Gui Add, CheckBox, vcolorWarperState g_set_color_warper_state x790 y120 w403 h23, Check this box if your color warper window is floating
Gui Add, Picture, x480 y480 w950 h400, %A_ScriptDir%\images\Sizing Input.png
Gui Add, Button, g_set_variable_button vpos_sizing_input_pan x352 y480 w120 h50, Pan
Gui Add, Button, g_set_variable_button vpos_sizing_input_tilt x352 y544 w120 h50, Tilt
Gui Add, Button, g_set_variable_button vpos_sizing_input_zoom x352 y608 w120 h50, Zoom
Gui Add, Button, g_set_variable_button vpos_sizing_input_rotate x352 y672 w120 h50, Rotate
Gui Add, Button, g_set_variable_button vpos_sizing_input_reset_sizing x984 y888 w120 h50, Reset Sizing
Gui Add, Button, g_set_variable_button vpos_sizing_input_width x816 y952 w120 h50, Width
Gui Add, Button, g_set_variable_button vpos_sizing_input_height x984 y952 w120 h50, Height
Gui Add, Button, g_set_variable_button vpos_sizing_input_pitch x816 y1016 w120 h50, Pitch
Gui Add, Button, g_set_variable_button vpos_sizing_input_yaw x984 y1016 w120 h50, Yaw
Gui Add, Button, g_set_variable_button vpos_sizing_input_horizontal_flip x816 y1080 w120 h50, h Flip
Gui Add, Button, g_set_variable_button vpos_sizing_input_vertical_flip x984 y1080 w120 h50, v Flip
Gui Add, Button, g_set_variable_button vpos_sizing_input_reset_blanking x1440 y512 w120 h50, Reset Blanking
Gui Add, Button, g_set_variable_button vpos_sizing_input_top x1440 y576 w120 h50, Top
Gui Add, Button, g_set_variable_button vpos_sizing_input_right x1440 y640 w120 h50, Right
Gui Add, Button, g_set_variable_button vpos_sizing_input_bottom x1440 y704 w120 h50, Bottom
Gui Add, Button, g_set_variable_button vpos_sizing_input_left x1440 y768 w120 h50, Left
Gui Add, Button, g_set_variable_button vpos_sizing_input_somooth x1440 y832 w120 h50, Smooth

Gui Show, w1920 h1249, TWB 2.5
Return

_start_stop_bt:
Return

_save_positions_bt:
Return

_enable_last_button:
Return

_add_combobox_items_input_box:
Return

_change_resolution_and_scale:
Return

_change_davinci_layout_ui:
Return

_change_curves_hash:
Return

_set_scopes_state:
Return

_set_color_warper_state:
Return

GuiEscape:
GuiClose:
    ExitApp
