; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s9, Segoe UI
Gui Add, Picture, x8 y8 w150 h150, %A_ScriptDir%\images\Logo.png
Gui Add, Text, x1200 y8 w700 h23 +0x200  , How to setup your own resolution (took aprox. 40 minutes):
Gui Add, Text, x1200 y31 w700 h23, 1 - Click on "Add New Resolution Config" Button and set a name for it
Gui Add, Text, x1200 y54 w700 h23, 2 - Click on the button of the tool that you will change the position
Gui Add, Text, x1200 y77 w700 h23, 3 - Go to your software screen and position the mouse on top of the tool
Gui Add, Text, x1200 y100 w700 h23, 4 - Hit "ENTER" key to save that position - If you think you made a mistake, you can hit "Enable Last Button" and do that tool again
Gui Add, Text, x1200 y123 w700 h23, 5 - Repeat the process for each tool and after do it for all the tools, hit "Save Positions" button
Gui Add, Text, x1200 y146 w700 h23, * Please wait 5 to 10 seconds to do anything else on the software after hit "Save Positions" button
Gui Add, Button, g_start_stop_bt x192 y8 w150 h50, Stop TWB
Gui Add, Button, g_save_positions_bt x192 y64 w150 h50, Save Positions
Gui Add, Button, g_enable_last_button x192 y120 w150 h50, Enable Last Button
Gui Add, Button, g_add_combobox_items_input_box x768 y8 w150 h50, Add New Resolution Config
Gui Add, Text, x360 y8 w250 h23, Set Resolution / DPI Scale (in percentage):
Gui Add, ComboBox, vcomboboxResolutionScale g_change_resolution_and_scale x360 y32 w400, %_comboboxItems%

Gui Add, Picture, x480 y232 w956 h406 +0x400000 , %A_ScriptDir%\images\Primaries Wheels Panel.png
Gui Add, Button, g_set_variable_button vpos_primaries_auto_balance x320 y352 w150 h50, Auto Balance
Gui Add, Button, g_set_variable_button vpos_primaries_awb_picker x320 y416 w150 h50, AWB Picker
Gui Add, Button, g_set_variable_button vpos_primaries_black_point_picker x488 y288 w150 h50, Black Point Picker
Gui Add, Button, g_set_variable_button vpos_primaries_white_point_picker x920 y288 w150 h50, White Point Picker
Gui Add, Button, g_set_variable_button vpos_primaries_lift_y x528 y768 w150 h50, Lift Y
Gui Add, Button, g_set_variable_button vpos_primaries_lift_r x528 y832 w150 h50 Lift R
Gui Add, Button, g_set_variable_button vpos_primaries_lift_g x528 y776 w150 h50, Lift G
Gui Add, Button, g_set_variable_button vpos_primaries_lift_b x528 y896 w150 h50, Lift B
Gui Add, Button, g_set_variable_button vpos_primaries_gamma_y x776 y648 w150 h50, Gamma Y
Gui Add, Button, g_set_variable_button vpos_primaries_gamma_r x776 y712 w150 h50, Gamma R
Gui Add, Button, g_set_variable_button vpos_primaries_gamma_g x776 y776 w150 h50, Gamma G
Gui Add, Button, g_set_variable_button vpos_primaries_gamma_b x776 y840 w150 h50, Gamma B
Gui Add, Button, g_set_variable_button vpos_primaries_gain_y x1008 y648 w150 h50, Gain Y
Gui Add, Button, g_set_variable_button vpos_primaries_gain_r x1008 y712 w150 h50, Gain R
Gui Add, Button, g_set_variable_button vpos_primaries_gain_g x1008 y776 w150 h50, Gain G
Gui Add, Button, g_set_variable_button vpos_primaries_gain_b x1008 y840 w150 h50, Gain B
Gui Add, Button, g_set_variable_button vpos_primaries_offset_r x1240 y648 w150 h50, Offset R
Gui Add, Button, g_set_variable_button vpos_primaries_offset_g x1240 y712 w150 h50, Offset G
Gui Add, Button, g_set_variable_button vpos_primaries_offset_b x1240 y776 w150 h50, Offset B

Gui Show, w1920 h1080, TWB 2.3
Return

_start_stop_bt:
Return

_save_positions_bt:
Return

_enable_last_button:
Return

_add_combobox_items_input_box:
Return

_change_resolution_and_scale:
Return

_set_variable_button:
Return

GuiEscape:
GuiClose:
    ExitApp
