; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s9, Segoe UI
Gui Add, Picture, x8 y8 w150 h150, %A_ScriptDir%\images\Logo.png
Gui Add, Text, x1200 y8 w700 h23 +0x200 , How to setup manually your own resolution:
Gui Add, Text, x1200 y31 w700 h23, 1 - Click on "Add New Resolution Config" Button and set a name for it
Gui Add, Text, x1200 y54 w700 h23, 2 - Click on the button of the tool that you will change the position
Gui Add, Text, x1200 y77 w700 h23, 3 - Go to your software screen and position the mouse on top of the tool
Gui Add, Text, x1200 y100 w700 h23, 4 - Hit "ENTER" key to save that position - If you think you made a mistake, you can hit "Enable Last Button" and do that tool again
Gui Add, Text, x1200 y123 w700 h23, 5 - Repeat the process for each tool and after do it for all the tools, hit "Save Positions" button
Gui Add, Text, x1200 y146 w700 h23, * Please wait 5 to 10 seconds to do anything else on the software after hit "Save Positions" button
Gui Add, Button, g_start_stop_bt x192 y8 w150 h50, Stop TWB
Gui Add, Button, g_save_positions_bt x192 y64 w150 h50, Save Positions
Gui Add, Button, g_enable_last_button x192 y120 w150 h50, Enable Last Button
Gui Add, Button, g_add_combobox_items_input_box x790 y8 w150 h50, Add New Resolution Config
Gui Add, Text, x360 y8 w250 h23, Set Resolution / DPI Scale (in percentage):
Gui Add, ComboBox, vcomboboxResolutionScale g_change_resolution_and_scale x360 y32 w400, %_comboboxResolutionItems%
Gui Add, Text, x360 y64 w250 h23, Set what is your Davinci Resolve Layout:
Gui Add, ComboBox, vcomboboxDavinciLayoutUI g_change_davinci_layout_ui x360 y90 w400, NORMAL|CONDENSED|WIDE
Gui Add, Text, x360 y120 w250 h23, Set a type of curves Hashs:
Gui Add, ComboBox, vcomboboxCurvesHashs g_change_curves_hash x360 y148 w100, 1|2|3
Gui Add, CheckBox, vscopesState g_set_scopes_state x790 y90 w403 h23, Check this box if your scopes window is floating
Gui Add, CheckBox, vcolorWarperState g_set_color_warper_state x790 y120 w403 h23, Check this box if your color warper window is floating
Gui Add, Picture, x184 y312 w950 h400, F:\André Rodrigues\Media Environment\Produtos\TWB 2 - Develop\GIT\develop\twb2.5\images\Color Warper Hue x Sat Panel.png
Gui Add, Button, vpos_color_warper_huexsat_dot g_set_variable_button x752 y248 w120 h50, Color Warper Hue x Sat
Gui Add, Button, vpos_color_warper_chrxlum_dot x880 y248 w120 h50, Color Warper Chr x Lum
Gui Add, Button, vpos_color_warper_reset_all x1008 y248 w120 h50, Color Warper Reset All
Gui Add, Button, vpos_color_warper_huexsat_select x1144 y320 w120 h50, Select / Deselect
Gui Add, Button, vpos_color_warper_huexsat_draw x1272 y320 w120 h50, Draw
Gui Add, Button, vpos_color_warper_huexsat_pin x1400 y320 w120 h50, Pin / De-pin
Gui Add, Button, vpos_color_warper_huexsat_pull x1528 y320 w120 h50, Pull Points
Gui Add, Button, vpos_color_warper_huexsat_push x1656 y320 w120 h50, Push Points
Gui Add, Button, vpos_color_warper_huexsat_increase_falloff x1144 y384 w120 h50, Increase Fall Off
Gui Add, Button, vpos_color_warper_huexsat_decrease_falloff x1272 y384 w120 h50, Decrease Fall Off
Gui Add, Button, vpos_color_warper_huexsat_invert_selection x1400 y384 w120 h50, Invert Selection
Gui Add, Button, vpos_color_warper_huexsat_convert_to_pin x1528 y384 w120 h50, Convert To Pin
Gui Add, Button, vpos_color_warper_huexsat_pin_column x1144 y448 w120 h50, Pin Column
Gui Add, Button, vpos_color_warper_huexsat_pin_ring x1272 y448 w120 h50, Pin Ring
Gui Add, Button, vpos_color_warper_huexsat_select_all x1400 y448 w120 h50, Select / Deselect All
Gui Add, Button, vpos_color_warper_huexsat_reset_selection x1528 y448 w120 h50, Reset Selection
Gui Add, Button, vpos_color_warper_huexsat_auto_lock x1144 y512 w120 h50, Auto Lock
Gui Add, Button, vpos_color_warper_huexsat_hue_bar x1144 y576 w120 h50, Hue Bar
Gui Add, Button, vpos_color_warper_huexsat_sat_bar x1272 y576 w120 h50, Saturation Bar
Gui Add, Button, vpos_color_warper_huexsat_lum_bar x1400 y576 w120 h50, Luma Bar
Gui Add, Button, vpos_color_warper_huexsat_hue_feather x1144 y640 w120 h50, Smooth Hue
Gui Add, Button, vpos_color_warper_huexsat_hue_reset x1272 y640 w120 h50, Reset Hue
Gui Add, Button, vpos_color_warper_huexsat_sat_feather x1400 y640 w120 h50, Smooth Saturation
Gui Add, Button, vpos_color_warper_huexsat_sat_reset x1528 y640 w120 h50, Reset Saturation
Gui Add, Button, vpos_color_warper_huexsat_lum_reset x1656 y640 w120 h50, Reset Luma
Gui Add, Button, vpos_color_warper_huexsat_hue_resolution x184 y720 w120 h50, Hue Resolution
Gui Add, Button, vpos_color_warper_huexsat_hue_resolution_1 x184 y784 w120 h40, Option 6
Gui Add, Button, vpos_color_warper_huexsat_hue_resolution_2 x184 y832 w120 h40, Option 8
Gui Add, Button, vpos_color_warper_huexsat_hue_resolution_3 x184 y880 w120 h40, Option 12
Gui Add, Button, vpos_color_warper_huexsat_hue_resolution_4 x184 y928 w120 h40, Option 16
Gui Add, Button, vpos_color_warper_huexsat_hue_resolution_5 x184 y976 w120 h40, Option 24
Gui Add, Button, vpos_color_warper_huexsat_sat_resolution x320 y720 w120 h50, Saturation Resolution
Gui Add, Button, vpos_color_warper_huexsat_sat_resolution_1 x320 y784 w120 h40, Option 6
Gui Add, Button, vpos_color_warper_huexsat_sat_resolution_2 x320 y832 w120 h40, Option 8
Gui Add, Button, vpos_color_warper_huexsat_sat_resolution_3 x320 y880 w120 h40, Option 12
Gui Add, Button, vpos_color_warper_huexsat_sat_resolution_4 x320 y928 w120 h40, Option 16
Gui Add, Button, vpos_color_warper_huexsat_color_space x664 y720 w120 h50, Color Space
Gui Add, Button, vpos_color_warper_huexsat_color_space_hsv x664 y784 w120 h40, HSV
Gui Add, Button, vpos_color_warper_huexsat_color_space_hsl x664 y832 w120 h40, HSL
Gui Add, Button, vpos_color_warper_huexsat_color_space_hsy x664 y880 w120 h40, HSY
Gui Add, Button, vpos_color_warper_huexsat_color_space_hsp x664 y928 w120 h40, HSP
Gui Add, Button, vpos_color_warper_huexsat_color_space_hsp_log x664 y976 w120 h40, HSP LOG

Gui Show, w1920 h1080, TWB 2.5
Return

_start_stop_bt:
Return

_save_positions_bt:
Return

_enable_last_button:
Return

_add_combobox_items_input_box:
Return

_change_resolution_and_scale:
Return

_change_davinci_layout_ui:
Return

_change_curves_hash:
Return

_set_scopes_state:
Return

_set_color_warper_state:
Return

_set_variable_button:
Return

GuiEscape:
GuiClose:
    ExitApp
