; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s9, Segoe UI
Gui Add, Picture, x8 y8 w150 h150, %A_ScriptDir%\images\Logo.png
Gui Add, Text, x1200 y8 w700 h23 +0x200  , How to setup your own resolution (took aprox. 40 minutes):
Gui Add, Text, x1200 y31 w700 h23, 1 - Click on "Add New Resolution Config" Button and set a name for it
Gui Add, Text, x1200 y54 w700 h23, 2 - Click on the button of the tool that you will change the position
Gui Add, Text, x1200 y77 w700 h23, 3 - Go to your software screen and position the mouse on top of the tool
Gui Add, Text, x1200 y100 w700 h23, 4 - Hit "ENTER" key to save that position - If you think you made a mistake, you can hit "Enable Last Button" and do that tool again
Gui Add, Text, x1200 y123 w700 h23, 5 - Repeat the process for each tool and after do it for all the tools, hit "Save Positions" button
Gui Add, Text, x1200 y146 w700 h23, * Please wait 5 to 10 seconds to do anything else on the software after hit "Save Positions" button
Gui Add, Button, g_start_stop_bt x192 y8 w150 h50, Stop TWB
Gui Add, Button, g_save_positions_bt x192 y64 w150 h50, Save Positions
Gui Add, Button, g_enable_last_button x192 y120 w150 h50, Enable Last Button
Gui Add, Button, g_add_combobox_items_input_box x768 y8 w150 h50, Add New Resolution Config
Gui Add, Text, x360 y8 w250 h23, Set Resolution / DPI Scale (in percentage):
Gui Add, ComboBox, vcomboboxResolutionScale g_change_resolution_and_scale x360 y32 w400, %_comboboxItems%

Gui Add, Picture, x480 y432 w950 h400, %A_ScriptDir%\images\BSM Panel.png
Gui Add, Button, g_set_variable_button vpos_bsm_blur_dot x960 y304 w150 h50, Blur Button
Gui Add, Button, g_set_variable_button vpos_bsm_sharpen_dot x1120 y304 w150 h50, Sharpen Button
Gui Add, Button, g_set_variable_button vpos_bsm_mist_dot x1280 y304 w150 h50, Mist Button
Gui Add, Button, g_set_variable_button vpos_bsm_radius_reset x640 y368 w150 h50, Radius Reset
Gui Add, Button, g_set_variable_button vpos_bsm_reset x1440 y432 w150 h50, Blur/Sharpen/Mist Reset
Gui Add, Button, g_set_variable_button vpos_bsm_scaling_r x1200 y848 w150 h50, Scaling R
Gui Add, Button, g_set_variable_button vpos_bsm_coring_softness x320 y656 w150 h50, Coring Softness
Gui Add, Button, g_set_variable_button vpos_bsm_radius_b x568 y976 w150 h50, Radius B
Gui Add, Button, g_set_variable_button vpos_bsm_radius_link x480 y368 w150 h50, Radius Link
Gui Add, Button, g_set_variable_button vpos_bsm_ratio_reset x960 y368 w150 h50, Ratio Reset
Gui Add, Button, g_set_variable_button vpos_bsm_scaling_g x1200 y912 w150 h50, Scaling G
Gui Add, Button, g_set_variable_button vpos_bsm_scaling_link x1120 y368 w150 h50, Scaling Link
Gui Add, Button, g_set_variable_button vpos_bsm_ratio_g x880 y912 w150 h50, Ratio G
Gui Add, Button, g_set_variable_button vpos_bsm_radius_r x568 y848 w150 h50, Radius R
Gui Add, Button, g_set_variable_button vpos_bsm_scaling_reset x1280 y368 w150 h50, Scaling Reset
Gui Add, Button, g_set_variable_button vpos_bsm_level x320 y720 w150 h50, Level
Gui Add, Button, g_set_variable_button vpos_bsm_mix x320 y784 w150 h50, Mix
Gui Add, Button, g_set_variable_button vpos_bsm_ratio_b x880 y976 w150 h50, Ratio B
Gui Add, Button, g_set_variable_button vpos_bsm_scaling_b x1200 y976 w150 h50, Scaling B
Gui Add, Button, g_set_variable_button vpos_bsm_ratio_link x800 y368 w150 h50, Ratio Link
Gui Add, Button, g_set_variable_button vpos_bsm_radius_g x568 y912 w150 h50, Radius G
Gui Add, Button, g_set_variable_button vpos_bsm_ratio_r x880 y848 w150 h50, Ratio R

Gui Show, w1920 h1080, TWB 2.3
Return

_start_stop_bt:
Return

_save_positions_bt:
Return

_enable_last_button:
Return

_add_combobox_items_input_box:
Return

_change_resolution_and_scale:
Return

_set_variable_button:
Return

GuiEscape:
GuiClose:
    ExitApp
