; Generated by Auto-GUI 3.0.0
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s9, Segoe UI
Gui Add, Picture, x8 y8 w150 h150, %A_ScriptDir%\images\Logo.png
Gui Add, Text, x1216 y8 w120 h23 +0x200 , How to use:
Gui Add, Text, x1216 y31 w700 h23, 1 - Click on the button of the tool that you want change the position
Gui Add, Text, x1216 y54 w700 h23, 2 - Go to your software screen and position the mouse on top of the tool
Gui Add, Text, x1216 y77 w700 h23, 3 - Hit "ENTER" key
Gui Add, Text, x1216 y100 w700 h23, 4 - If you think you made a mistake, you can hit Enable Last Button and do that position again
Gui Add, Text, x1216 y123 w700 h23, 5 - Repeat the process for each tool and hit "Save Positions" button at the end
Gui Add, Button, g_start_stop_bt x192 y8 w150 h50, Start TWB
Gui Add, Button, g_save_positions_bt x192 y64 w150 h50, Save Positions
Gui Add, Button, genableLastButton x192 y120 w150 h50, Enable Last Button
Gui Add, Button, g_checkRes x600 y100 w150 h50, Check Res Test Button
Gui Add, Text, x360 y8 w250 h23, Set Resolution / DPI Scale (in percentage):

Gui Add, Picture, x448 y568 w100 h65, %A_ScriptDir%\images\Cursor and Hand.png
Gui Add, Picture, x1056 y504 w200 h100, %A_ScriptDir%\images\Nodes Menu 1.png
Gui Add, Picture, x1392 y504 w200 h145, %A_ScriptDir%\images\Nodes Menu 2.png
Gui Add, Button, g_set_variable_button vpos_color_interface_tools_cursor_mode x320 y576 w120 h50, Cursor Mode
Gui Add, Button, g_set_variable_button vpos_color_interface_tools_hand_mode x560 y576 w120 h50, Hand Mode
Gui Add, Button, g_set_variable_button vpos_color_interface_tools_node_mode_menu x928 y504 w120 h50, Nodes Menu
Gui Add, Button, g_set_variable_button vpos_color_interface_tools_node_mode_1 x1264 y504 w120 h50, Nodes Mode 1
Gui Add, Button, g_set_variable_button vpos_color_interface_tools_node_mode_2 x1264 y568 w120 h50, Nodes Mode 2
Gui Add, Button, g_set_variable_button vpos_color_interface_tools_node_mode_3 x1264 y632 w120 h50, Nodes Mode 3
Gui Add, Button, g_set_variable_button vpos_color_interface_tools_node_mode_4 x1264 y696 w120 h50, Nodes Mode 4


Gui Show, w1920 h1080, TWB 2.0 Beta
Return

save_positions_bt:
Return

start_stop_bt:
Return

changeResolutionAndScale:
Return

GuiEscape:
GuiClose:
    ExitApp
