; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s9, Segoe UI
Gui Add, Text, x0 y100 w1278 h2 +0x10 
Gui Add, Text, x0 y0 w1024 h100 +0x200 +Center , How's your Davinci UI looks like on color page?
Gui Add, Picture, x282 y165 w460 h437, F:\André Rodrigues\Media Environment\Produtos\TWB 2 - Develop\GIT\develop\twb2.4\images\step-by-step\pos_zone_on_off_highlight.png

Gui Show, w1024 h768, Window
Return

_set_variable_button:
Return

GuiEscape:
GuiClose:
    ExitApp
