; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

    Gui Font, s9, Segoe UI
    Gui Add, Text, x0 y0 w1024 h768
    Gui Add, Text, x0 y100 w1280 h3 +0x10
    Gui Add, Text, x0 y0 w1024 h100 +0x200 +Center, How's your Davinci UI looks like on color page?
    Gui Add, Picture, x368 y250 w1024 h485, %A_ScriptDir%\images\step-by-step\davinci_condensed_interface.png
    Gui Add, Button, g_set_variable_button x80 y464 w200 h50, Normal Layout
    Gui Add, Button, g_set_variable_button x450 y464 w200 h50, Condensed Layout
    
    Gui Show, w1024 h768, Window
Return

_set_variable_button:
Return

GuiEscape:
GuiClose:
    ExitApp
